/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('antdv-next')['Avatar']
    AButton: typeof import('antdv-next')['Button']
    ACard: typeof import('antdv-next')['Card']
    ACol: typeof import('antdv-next')['Col']
    AConfigProvider: typeof import('antdv-next')['ConfigProvider']
    ADropdown: typeof import('antdv-next')['Dropdown']
    AForm: typeof import('antdv-next')['Form']
    AFormItem: typeof import('antdv-next')['FormItem']
    AInput: typeof import('antdv-next')['Input']
    AInputPassword: typeof import('antdv-next')['InputPassword']
    AMenu: typeof import('antdv-next')['Menu']
    AMenuDivider: typeof import('antdv-next')['MenuDivider']
    AMenuItem: typeof import('antdv-next')['MenuItem']
    AMenuItemGroup: typeof import('antdv-next')['MenuItemGroup']
    ARow: typeof import('antdv-next')['Row']
    BaseBarChart: typeof import('./components/charts/BaseBarChart.vue')['default']
    BaseLineChart: typeof import('./components/charts/BaseLineChart.vue')['default']
    BasePieChart: typeof import('./components/charts/BasePieChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeToggle: typeof import('./components/ThemeToggle.vue')['default']
  }
}
