/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAlert: typeof import('antdv-next')['Alert']
    AAvatar: typeof import('antdv-next')['Avatar']
    ABreadcrumb: typeof import('antdv-next')['Breadcrumb']
    ABreadcrumbItem: typeof import('antdv-next')['BreadcrumbItem']
    AButton: typeof import('antdv-next')['Button']
    ACard: typeof import('antdv-next')['Card']
    ACol: typeof import('antdv-next')['Col']
    AConfigProvider: typeof import('antdv-next')['ConfigProvider']
    ADrawer: typeof import('antdv-next')['Drawer']
    ADropdown: typeof import('antdv-next')['Dropdown']
    AEmpty: typeof import('antdv-next')['Empty']
    AForm: typeof import('antdv-next')['Form']
    AFormItem: typeof import('antdv-next')['FormItem']
    AInput: typeof import('antdv-next')['Input']
    AInputPassword: typeof import('antdv-next')['InputPassword']
    ALayout: typeof import('antdv-next')['Layout']
    ALayoutContent: typeof import('antdv-next')['LayoutContent']
    ALayoutHeader: typeof import('antdv-next')['LayoutHeader']
    ALayoutSider: typeof import('antdv-next')['LayoutSider']
    AMenu: typeof import('antdv-next')['Menu']
    AMenuDivider: typeof import('antdv-next')['MenuDivider']
    AMenuItem: typeof import('antdv-next')['MenuItem']
    AMenuItemGroup: typeof import('antdv-next')['MenuItemGroup']
    AModal: typeof import('antdv-next')['Modal']
    APopover: typeof import('antdv-next')['Popover']
    AProgress: typeof import('antdv-next')['Progress']
    ARadioButton: typeof import('antdv-next')['RadioButton']
    ARadioGroup: typeof import('antdv-next')['RadioGroup']
    ARangePicker: typeof import('antdv-next')['DateRangePicker']
    ARow: typeof import('antdv-next')['Row']
    ArrowLeftOutlined: typeof import('@antdv-next/icons')['ArrowLeftOutlined']
    ASegmented: typeof import('antdv-next')['Segmented']
    ASelect: typeof import('antdv-next')['Select']
    ASkeleton: typeof import('antdv-next')['Skeleton']
    ASlider: typeof import('antdv-next')['Slider']
    ASpace: typeof import('antdv-next')['Space']
    ASpin: typeof import('antdv-next')['Spin']
    ATable: typeof import('antdv-next')['Table']
    ATag: typeof import('antdv-next')['Tag']
    ATooltip: typeof import('antdv-next')['Tooltip']
    AudioOutlined: typeof import('@antdv-next/icons')['AudioOutlined']
    BaseBarChart: typeof import('./components/charts/BaseBarChart.vue')['default']
    BaseLineChart: typeof import('./components/charts/BaseLineChart.vue')['default']
    BasePieChart: typeof import('./components/charts/BasePieChart.vue')['default']
    CalendarOutlined: typeof import('@antdv-next/icons')['CalendarOutlined']
    CheckCircleFilled: typeof import('@antdv-next/icons')['CheckCircleFilled']
    ClockCircleOutlined: typeof import('@antdv-next/icons')['ClockCircleOutlined']
    CloseOutlined: typeof import('@antdv-next/icons')['CloseOutlined']
    DesktopOutlined: typeof import('@antdv-next/icons')['DesktopOutlined']
    DragOutlined: typeof import('@antdv-next/icons')['DragOutlined']
    FilterBar: typeof import('./components/FilterBar.vue')['default']
    FilterField: typeof import('./components/FilterField.vue')['default']
    PlayCircleOutlined: typeof import('@antdv-next/icons')['PlayCircleOutlined']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StopOutlined: typeof import('@antdv-next/icons')['StopOutlined']
    TeamOutlined: typeof import('@antdv-next/icons')['TeamOutlined']
    ThemePalette: typeof import('./components/ThemePalette.vue')['default']
    ThemeToggle: typeof import('./components/ThemeToggle.vue')['default']
    TitleBar: typeof import('./components/TitleBar.vue')['default']
    UserAddOutlined: typeof import('@antdv-next/icons')['UserAddOutlined']
    UserMenu: typeof import('./components/UserMenu.vue')['default']
  }
}
