/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('antdv-next')['Button']
    ACard: typeof import('antdv-next')['Card']
    ACol: typeof import('antdv-next')['Col']
    AConfigProvider: typeof import('antdv-next')['ConfigProvider']
    AEmpty: typeof import('antdv-next')['Empty']
    AForm: typeof import('antdv-next')['Form']
    AFormItem: typeof import('antdv-next')['FormItem']
    AInput: typeof import('antdv-next')['Input']
    ARadioButton: typeof import('antdv-next')['RadioButton']
    ARadioGroup: typeof import('antdv-next')['RadioGroup']
    ARow: typeof import('antdv-next')['Row']
    ASelect: typeof import('antdv-next')['Select']
    ATag: typeof import('antdv-next')['Tag']
    BaseBarChart: typeof import('./components/charts/BaseBarChart.vue')['default']
    BaseLineChart: typeof import('./components/charts/BaseLineChart.vue')['default']
    BasePieChart: typeof import('./components/charts/BasePieChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeToggle: typeof import('./components/ThemeToggle.vue')['default']
  }
}
